# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
      - run:
        name: Maven build
        command: mvn -B package --file pom.xml
      - run:
        name: Set jacoco.xml path for code climate
        command: JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./target/site/jacoco/jacoco.xml --input-type jacoco
      - run:
        name: Upload code climate report
        command: ./cc-test-reporter upload-coverage -r 190770491d0b797ee0b1801f408b0f75bef52d599cd893d31b83ac27b1629a1a
        when: on_success